name: Testing config overrides
type: profile
description: 'Minimal profile for running tests with config overrides in a profile.'
version: VERSION
core: 8.x
hidden: true
install:
  - action
  - language
  - tour

# Information added by drush on 2019-02-20
version: '8.6.10'
project: 'drupal'
datestamp: 1550687701